-- Journal de l'exécution du 2026-09-08 14:45:48
-- (déjà appliqué directement en base — ce fichier est juste une trace lisible, ne pas le réimporter.)

-- Nouveaux joueurs/joueuses (ATP + WTA) :
INSERT INTO player (id, full_name, country_code, atp_wta_rank, elo_overall, elo_hard, elo_clay, elo_grass, dominant_hand, external_ref, tour) VALUES (147, 'Carlos Alcaraz', 'esp', 3, 2312, 2247, 2276, 2225, 'R', 'tml:A0E2', 'atp');
INSERT INTO player (id, full_name, country_code, atp_wta_rank, elo_overall, elo_hard, elo_clay, elo_grass, dominant_hand, external_ref, tour) VALUES (148, 'Alexander Zverev', 'ger', 2, 2066, 2078, 2061, 1975, 'R', 'tml:Z355', 'atp');
INSERT INTO player (id, full_name, country_code, atp_wta_rank, elo_overall, elo_hard, elo_clay, elo_grass, dominant_hand, external_ref, tour) VALUES (149, 'Botic Van De Zandschulp', 'ned', 70, 1794, 1796, 1799, 1800, 'R', 'tml:V812', 'atp');
INSERT INTO player (id, full_name, country_code, atp_wta_rank, elo_overall, elo_hard, elo_clay, elo_grass, dominant_hand, external_ref, tour) VALUES (150, 'Karen Khachanov', NULL, 50, 1899, 1870, 1946, 1908, 'R', 'tml:KE29', 'atp');
INSERT INTO player (id, full_name, country_code, atp_wta_rank, elo_overall, elo_hard, elo_clay, elo_grass, dominant_hand, external_ref, tour) VALUES (151, 'Alexander Blockx', 'bel', 34, 1625, 1642, 1582, 1572, 'R', 'tml:B0PG', 'atp');
INSERT INTO player (id, full_name, country_code, atp_wta_rank, elo_overall, elo_hard, elo_clay, elo_grass, dominant_hand, external_ref, tour) VALUES (152, 'Aryna Sabalenka', NULL, 1, 2208, 2298, 2137, 2041, 'R', 'wta:214544', 'wta');

-- Joueurs existants dont l'Elo (et/ou le circuit, voir resolve_player) a été rafraîchi :
UPDATE player SET elo_overall=1849, elo_hard=1847, elo_clay=1887, elo_grass=1892, atp_wta_rank=12, tour='atp' WHERE id=18;
UPDATE player SET elo_overall=1817, elo_hard=1830, elo_clay=1645, elo_grass=1788, atp_wta_rank=46, tour='atp' WHERE id=17;
UPDATE player SET elo_overall=1965, elo_hard=1960, elo_clay=1857, elo_grass=1811, atp_wta_rank=9, tour='atp' WHERE id=5;
UPDATE player SET elo_overall=2076, elo_hard=1994, elo_clay=1841, elo_grass=1992, atp_wta_rank=6, tour='wta' WHERE id=34;
UPDATE player SET elo_overall=2148, elo_hard=2176, elo_clay=2003, elo_grass=2044, atp_wta_rank=3, tour='wta' WHERE id=28;
UPDATE player SET elo_overall=2171, elo_hard=2199, elo_clay=2104, elo_grass=1972, atp_wta_rank=4, tour='wta' WHERE id=20;
UPDATE player SET elo_overall=2086, elo_hard=2017, elo_clay=2114, elo_grass=1788, atp_wta_rank=5, tour='wta' WHERE id=33;

-- Nouveaux matchs à venir (ATP + WTA) :
INSERT INTO tennis_match (id, player_a_id, player_b_id, winner_id, tournament_name, round, surface, scheduled_at, status, score_text, external_ref) VALUES (94, 18, 17, NULL, 'US Open', 'Quart de finale', 'dur', '2026-09-08 17:00:00', 'scheduled', NULL, 'livetennisapi:187553');
INSERT INTO tennis_match (id, player_a_id, player_b_id, winner_id, tournament_name, round, surface, scheduled_at, status, score_text, external_ref) VALUES (95, 5, 147, NULL, 'US Open', 'Quart de finale', 'dur', '2026-09-09 00:30:00', 'scheduled', NULL, 'livetennisapi:187552');
INSERT INTO tennis_match (id, player_a_id, player_b_id, winner_id, tournament_name, round, surface, scheduled_at, status, score_text, external_ref) VALUES (96, 148, 149, NULL, 'US Open', 'Quart de finale', 'dur', '2026-09-09 15:30:00', 'scheduled', NULL, 'livetennisapi:188143');
INSERT INTO tennis_match (id, player_a_id, player_b_id, winner_id, tournament_name, round, surface, scheduled_at, status, score_text, external_ref) VALUES (97, 150, 151, NULL, 'US Open', 'Quart de finale', 'dur', '2026-09-09 15:30:00', 'scheduled', NULL, 'livetennisapi:188123');
INSERT INTO tennis_match (id, player_a_id, player_b_id, winner_id, tournament_name, round, surface, scheduled_at, status, score_text, external_ref) VALUES (98, 152, 34, NULL, 'US Open', 'Quart de finale', 'dur', '2026-09-08 15:30:00', 'scheduled', NULL, 'livetennisapi:187454');
INSERT INTO tennis_match (id, player_a_id, player_b_id, winner_id, tournament_name, round, surface, scheduled_at, status, score_text, external_ref) VALUES (99, 28, 29, NULL, 'US Open', 'Quart de finale', 'dur', '2026-09-08 23:00:00', 'scheduled', NULL, 'livetennisapi:187554');
INSERT INTO tennis_match (id, player_a_id, player_b_id, winner_id, tournament_name, round, surface, scheduled_at, status, score_text, external_ref) VALUES (100, 35, 140, NULL, 'US Open', 'Quart de finale', 'dur', '2026-09-09 15:00:00', 'scheduled', NULL, 'livetennisapi:188072');
INSERT INTO tennis_match (id, player_a_id, player_b_id, winner_id, tournament_name, round, surface, scheduled_at, status, score_text, external_ref) VALUES (101, 20, 33, NULL, 'US Open', 'Quart de finale', 'dur', '2026-09-09 15:30:00', 'scheduled', NULL, 'livetennisapi:188117');

-- Nouvelles analyses :
INSERT INTO prediction (id, match_id, favorite_player_id, probability_favorite, confidence_level, model_version, computed_at, explanation_factors, radar_profile, market_odds_favorite, value_edge) VALUES (31, 94, 17, 0.5564, 'moyen', 'xgboost-v1-2026.08', NOW(), '[{"label": "Classement ATP", "favors": "B", "impactPoints": 3.4, "tone": "ok"}, {"label": "Face-à-face", "favors": "A", "impactPoints": -2, "tone": "warn"}, {"label": "Dynamique du moment (Elo sur les derniers matchs)", "favors": "B", "impactPoints": 8.2, "tone": "ok"}]', '{"eloSurface": [43, 41], "forme": [58, 51], "service": [63, 62], "retour": [37, 37], "repos": [99, 99], "h2h": [70, 30]}', NULL, NULL);
INSERT INTO prediction (id, match_id, favorite_player_id, probability_favorite, confidence_level, model_version, computed_at, explanation_factors, radar_profile, market_odds_favorite, value_edge) VALUES (32, 95, 147, 0.7372, 'eleve', 'xgboost-v1-2026.08', NOW(), '[{"label": "Classement ATP", "favors": "B", "impactPoints": 0.6, "tone": "ok"}, {"label": "Face-à-face", "favors": "B", "impactPoints": 3, "tone": "ok"}, {"label": "Dynamique du moment (Elo sur les derniers matchs)", "favors": "B", "impactPoints": 1.9, "tone": "ok"}, {"label": "Habitude du jeu face à un gaucher", "favors": "B", "impactPoints": 1.7, "tone": "ok"}, {"label": "Capacité à créer l\'exploit contre plus fort classé", "favors": "B", "impactPoints": 3.3, "tone": "ok"}]', '{"eloSurface": [57, 93], "forme": [59, 85], "service": [66, 66], "retour": [35, 42], "repos": [99, 99], "h2h": [20, 80]}', NULL, NULL);
INSERT INTO prediction (id, match_id, favorite_player_id, probability_favorite, confidence_level, model_version, computed_at, explanation_factors, radar_profile, market_odds_favorite, value_edge) VALUES (33, 96, 148, 0.7754, 'eleve', 'xgboost-v1-2026.08', NOW(), '[{"label": "Classement ATP", "favors": "A", "impactPoints": 6.8, "tone": "ok"}]', '{"eloSurface": [72, 37], "forme": [71, 45], "service": [66, 60], "retour": [38, 37], "repos": [99, 99], "h2h": [50, 50]}', NULL, NULL);
INSERT INTO prediction (id, match_id, favorite_player_id, probability_favorite, confidence_level, model_version, computed_at, explanation_factors, radar_profile, market_odds_favorite, value_edge) VALUES (34, 97, 150, 0.7062, 'eleve', 'xgboost-v1-2026.08', NOW(), '[{"label": "Classement ATP", "favors": "A", "impactPoints": 1.6, "tone": "ok"}, {"label": "Dynamique du moment (Elo sur les derniers matchs)", "favors": "B", "impactPoints": -11.6, "tone": "warn"}]', '{"eloSurface": [46, 18], "forme": [61, 38], "service": [64, 62], "retour": [39, 29], "repos": [99, 99], "h2h": [50, 50]}', NULL, NULL);
INSERT INTO prediction (id, match_id, favorite_player_id, probability_favorite, confidence_level, model_version, computed_at, explanation_factors, radar_profile, market_odds_favorite, value_edge) VALUES (35, 98, 152, 0.6676, 'eleve', 'xgboost-v1-2026.08', NOW(), '[{"label": "Classement WTA", "favors": "A", "impactPoints": 0.5, "tone": "ok"}, {"label": "Face-à-face", "favors": "A", "impactPoints": 2, "tone": "ok"}, {"label": "Dynamique du moment (Elo sur les derniers matchs)", "favors": "B", "impactPoints": -6.8, "tone": "warn"}]', '{"eloSurface": [99, 62], "forme": [82, 63], "service": [61, 59], "retour": [46, 43], "repos": [99, 99], "h2h": [70, 30]}', NULL, NULL);
INSERT INTO prediction (id, match_id, favorite_player_id, probability_favorite, confidence_level, model_version, computed_at, explanation_factors, radar_profile, market_odds_favorite, value_edge) VALUES (36, 99, 28, 0.7473, 'eleve', 'xgboost-v1-2026.08', NOW(), '[{"label": "Classement WTA", "favors": "A", "impactPoints": 2.4, "tone": "ok"}]', '{"eloSurface": [84, 39], "forme": [74, 65], "service": [59, 60], "retour": [47, 60], "repos": [99, 30], "h2h": [50, 50]}', NULL, NULL);
INSERT INTO prediction (id, match_id, favorite_player_id, probability_favorite, confidence_level, model_version, computed_at, explanation_factors, radar_profile, market_odds_favorite, value_edge) VALUES (37, 100, 35, 0.931, 'eleve', 'xgboost-v1-2026.08', NOW(), '[{"label": "Classement WTA", "favors": "A", "impactPoints": 11.9, "tone": "ok"}]', '{"eloSurface": [93, 30], "forme": [65, 65], "service": [60, 60], "retour": [60, 60], "repos": [30, 30], "h2h": [50, 50]}', NULL, NULL);
INSERT INTO prediction (id, match_id, favorite_player_id, probability_favorite, confidence_level, model_version, computed_at, explanation_factors, radar_profile, market_odds_favorite, value_edge) VALUES (38, 101, 20, 0.6193, 'moyen', 'xgboost-v1-2026.08', NOW(), '[{"label": "Classement WTA", "favors": "A", "impactPoints": 0.1, "tone": "ok"}, {"label": "Face-à-face", "favors": "A", "impactPoints": 5, "tone": "ok"}, {"label": "Dynamique du moment (Elo sur les derniers matchs)", "favors": "A", "impactPoints": 6.1, "tone": "ok"}]', '{"eloSurface": [87, 65], "forme": [76, 71], "service": [58, 59], "retour": [49, 48], "repos": [99, 99], "h2h": [99, 1]}', NULL, NULL);
