parameters:
    frontend_base_url: '%env(default::FRONTEND_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\StripeCheckoutService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
            $frontendBaseUrl: '%frontend_base_url%'

    App\Controller\StripeWebhookController:
        arguments:
            $stripeWebhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'
